### ISSUE TITLE
Java 7 cache problem

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/Porphyry#13] opened 2012-06-27 14:44 UTC
When used with Java 7, Porphyry returns errors message such as java.lang.RuntimeException: java.lang.NullPointerException
Those messages occurs namely when the user tries to connect to a (Dolomite) password-protected Cassandre server. 

When the console is open, a complementary message gives : 
CacheEntry : updateAvailable=false,lastModified=Wed Nov 25 11:12:25 CET 2009,length=-1

**Comment by christophe-lejeune** [comment] 2012-06-27 14:49
Aurélien Bénel discovers that this problem seems connected to a cache issue under Java 7. The error disappears when Java temporary files are suppressed. 

However, the problem occurs again and again so that Porphyry becomes unusable. 

## Workaround

A work around consists in disabling the temporary files saving (through Java control panel).

**Comment by benel** [comment] 2012-07-09 08:18
In Java 7 update 5, there seems to be very high priority [known bugs](http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7177094) related to HTTP cache and secure access.

Let's wait for the next update.

**Comment by benel** [comment] 2012-12-01 14:19
The bug in Java is supposed to be fixed, but the problem is still there :(

**Comment by benel** [comment] 2016-03-17 06:46
@christophe-lejeune Is it fixed with Java 8?

**Comment by christophe-lejeune** [comment] 2016-03-17 06:55
Not to my knowledge :-/

**Comment by benel** [comment] 2016-03-17 07:04
OK, I will test it.

**Closed as completed** 2017-06-14 21:22 UTC
Labels: Fix
