### ISSUE TITLE
Add audio resource to an image resource

### ISSUE THREAD

**Issue by LucasJeanpierre** [Hypertopic/Porphyry#568] opened 2022-03-18 08:34 UTC
### Description

Have the possibility to add an audio resource attach to an image resource

#### What is the valuable outcome that cannot be achieved with current features?

Have additional information about a resource

#### For which stakeholder (people, role, project, domain) is it important?

the audio resource will be important for every visitor, but only the administrator can add an audio resource

#### Which user action should be enabled (or restricted)? For who?

No restriction

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### Phase 3
- [ ] Screencast

**Comment by benel** [comment] 2022-03-18 10:25
This seems to be a special use of the following feature: #142. 
If it is such a duplicate, please close your ticket, and replace it with #142 in your kanban.

**Comment by benel** [comment] 2022-04-06 13:54
@Hypertopic/vitraux-de-troyes 

This seems to be a special use of the following feature: https://github.com/Hypertopic/Porphyry/issues/142.
If it is such a duplicate, please close your ticket, and replace it with https://github.com/Hypertopic/Porphyry/issues/142 in your kanban.

**Comment by Couapy** [comment] 2022-04-08 07:03
Duplicate of #142.
We updated our kanban.

**Closed as completed by Couapy** 2022-04-08 07:03 UTC
Labels: Feature
